openapi: '3.0.2'

info:
  title: API Kubera
  version: 1.0.0

servers:
  - url: http://localhost:8181
    description: Local


components:
  parameters:    
    AcceptHeader:
      name: Accept
      in: header
      description: Tipo de contenido aceptado, tiene que ser <b>application/json</b>.
      required: true
      schema:
        type: string
        example: application/json
  responses:
    UnauthorizedError:
      description: En caso de usar un token incorrecto.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Error example"
    InternalServerError:
      description: Error interno.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Error example"
    NotValidUrl:
      description: Error en la url.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Error example"
  schemas:
tags:

paths:
  '/api/mystery-box/category':
    get:
      description: Obtener categorías.
      parameters:
        - $ref: '#/components/parameters/AcceptHeader'
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    example: true
                    type: boolean
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/NotValidUrl'
        '400':
          $ref: '#/components/responses/InternalServerError'
  '/api/mystery-box/steam/user':
    post:
      description: Almacena el nombre de usuario o por lo menos el id de steam en bbdd asociado a la ip y devuelve true o false en caso de poder acceder a la info del usuario o no.
      parameters:
        - $ref: '#/components/parameters/AcceptHeader'
        - in: query
          name: id
          required: false
          schema:
            type: string
          description: El id del usuario o el nombre en steam (en el front mostrar como se obtiene el id).
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    example: true
                    type: boolean
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/NotValidUrl'
        '400':
          $ref: '#/components/responses/InternalServerError'
  '/api/mystery-box/user/{user_id}/search-matchs':
    get:
      description: Busca 2 juegos que estén bien valorados en steam, que haya una key por menos de lo que valen en kinguin y los almacenamos en 2 registros en bbdd asociados a el id del usuario que hemos almacenado en el registro anterior (junto con los datos del usuario habremos solicitado el email, esto va junto con el pago, que está para desarrollar más adelante). Esto verifica de la bbdd de hucha el dinero acumulado y hace un ramdom en caso de que haya suficiente para darle una recompensa. <br> Hay que <b>validar</b> desde back que la información de compra permite realizar esta búsqueda, que no se ha realizado ya y que la opción solicita existe y que no ha sido retornada con anterioridad.
      parameters:
        - $ref: '#/components/parameters/AcceptHeader'
        - in: path
          name: user_id
          required: true
          schema:
            type: string
          description: El id del usuario en nuestro sistema.
        - in: query
          required: true
          name: categories
          schema:
            type: string
            example: 12,32,56,78
          description: Una lista separada por comas de los identificadores de las categorías seleccionadas
        - in: query
          name: option
          required: false
          schema:
            type: integer
            default: 1
          description: Límit 2
        - in: query
          name: datos_necesarios_asociados_al_pago
          required: false
          schema:
            type: string
          description: Aun a definir
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    example: true
                    type: boolean
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/NotValidUrl'
        '400':
          $ref: '#/components/responses/InternalServerError'
  '/api/mystery-box/search-matchs/option/{option_id}':
    post:
      description: Esto hay que lanzarlo y tiene que quedar escuchando el front con un websocket. Al devolver opción tiene que marcarla en bbdd como la correcta y marcar la búsqueda como utilizada y mandar un mail con la key y mostrarla con el websocket
      parameters:
        - $ref: '#/components/parameters/AcceptHeader'
        - in: query
          name: datos_necesarios_asociados_al_pago
          required: false
          schema:
            type: string
          description: Aun a definir
      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    example: true
                    type: boolean
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '422':
          $ref: '#/components/responses/NotValidUrl'
        '400':
          $ref: '#/components/responses/InternalServerError'
